[workspace]
members = [".", "derive"]
[package]
name = "quix"
version = "0.1.0"
authors = ["Michal Hornicky <mhornick@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive = { path = "./derive" }

uuid = { version = "*", features = ["v4"] }
log = "*"
env_logger = "*"
prost = { version = "0.6.1", features = [] }
bytes = "*"
futures = "*"

actix = "0.10"
actix-rt = "1.1.1"
actix-codec = "0.3.0"

serde = "*"
tokio = { version = "*" }
tokio-util = { version = "*", features = ["codec"] }
json = { package = "serde_json", version = "*" }